openapi: 3.0.1
info:
  title: Hello Security API
  description: Public API for testing Micronat OpenAPI/Swagger for authenticated routes
  version: "1.0"
servers:
- url: https://example.com
tags:
- name: /hello
paths:
  /hello/authenticated/{helloId}:
    post:
      tags:
      - /hello
      operationId: authenticated
      parameters:
      - name: helloId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        default:
          content:
            application/json: {}
