openapi: 3.0.1
info:
  title: Hello Security API
  description: Public API for testing Micronat OpenAPI/Swagger for authenticated routes
  version: "1.0"
servers:
- url: https://example.com
tags:
- name: /hello
paths:
  /authenticated:
    post:
      tags:
      - /hello
      operationId: authenticated
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication:
                  $ref: '#/components/schemas/Authentication'
                gameReference:
                  $ref: '#/components/schemas/GameReference'
        required: true
      responses:
        default:
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Authentication:
      type: object
    GameReference:
      type: object
      properties:
        referenceId:
          type: string
        name:
          type: string
