openapi: 3.0.1
info:
  title: Hello Security API
  description: Public API for testing Micronat OpenAPI/Swagger for authenticated routes
  version: "1.0"
servers:
- url: https://example.com
tags:
- name: /hello
paths:
  /hello/authenticated:
    post:
      tags:
      - /hello
      operationId: authenticated
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        id:
          type: string
        properties:
          $ref: '#/components/schemas/Map<String,String>'
    Map<String,String>:
      type: object
